### ISSUE TITLE
Failed both services on MacBook M1 Pro

### ISSUE THREAD

**Issue by jspenaq** [corca-ai/EVAL#41]
**Description**
EVAL fails to execute in both services (eval and eval.gpu) on a MacBook M1 Pro running Ventura 13.3.

**Screenshots and Tracebacks**
I run: `docker-compose up --build eval` and get this:

![image](https://user-images.githubusercontent.com/36420972/230927401-ae45ee92-ba7c-4719-a020-c5c5f08ec190.png)

Traceback:
```
Attaching to eval
eval  | Traceback (most recent call last):
eval  |   File "<string>", line 1, in <module>
eval  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
eval  |     return _bootstrap._gcd_import(name[level:], package, level)
eval  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
eval  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
eval  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
eval  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
eval  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
eval  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
eval  |   File "/app/api/main.py", line 12, in <module>
eval  |     from api.container import agent_manager, file_handler, reload_dirs, templates, uploader
eval  |   File "/app/api/container.py", line 31, in <module>
eval  |     import torch
eval  | ModuleNotFoundError: No module named 'torch'
eval exited with code 1
```

I run `docker-compose up --build eval.gpu` and get this:

![image](https://user-images.githubusercontent.com/36420972/230927683-2e684681-21e8-48cf-b1e9-5ca17dfa134c.png)

Traceback:
```
#0 16.26   running build_ext
#0 16.26   building 'psutil._psutil_linux' extension
#0 16.26   creating build/temp.linux-aarch64-cpython-310
#0 16.26   creating build/temp.linux-aarch64-cpython-310/psutil
#0 16.26   aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=594 -DPy_LIMITED_API=0x03060000 -DPSUTIL_LINUX=1 -I/tmp/tmpd9wx01j8/.venv/include -I/usr/include/python3.10 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-310/psutil/_psutil_common.o
#0 16.26   psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
#0 16.26       9 | #include <Python.h>
#0 16.26         |          ^~~~~~~~~~
#0 16.26   compilation terminated.
#0 16.26   error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
#0 16.26
#0 16.26
#0 16.26   at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/installation/chef.py:152 in _prepare
#0 16.26       148│
#0 16.26       149│                 error = ChefBuildError("\n\n".join(message_parts))
#0 16.26       150│
#0 16.26       151│             if error is not None:
#0 16.26     → 152│                 raise error from None
#0 16.26       153│
#0 16.26       154│             return path
#0 16.26       155│
#0 16.26       156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
#0 16.26
#0 16.26 Note: This error originates from the build backend, and is likely not a problem with poetry but with psutil (5.9.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psutil (==5.9.4)"'.
#0 16.26 Note: This error originates from the build backend, and is likely not a problem with poetry but with psutil (5.9.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psutil (==5.9.4)"'.
#0 16.26
```

**Desktop:**
 - OS: macOS Ventura 13.3

Can someone help with this issue? Thanks!

**Comment by adldotori** [comment]
Sorry for this issue. We know that but we didn't fix yet. Could you run only service "eval" plz? We'll fix this problem as soon as possible.
