### ISSUE TITLE
can't install EVAL

### ISSUE THREAD

**Issue by shouwangzhe** [corca-ai/EVAL#54]
**command**： docker-compose up --build eval
**error**：
```
13.95 Setting up polkitd (122-3) ...
13.96 Creating group 'polkitd' with GID 996.
13.96 Creating user 'polkitd' (polkit) with UID 996 and GID 996.
13.99 invoke-rc.d: could not determine current runlevel
13.99 invoke-rc.d: policy-rc.d denied execution of reload.
14.17 start-stop-daemon: unable to stat /usr/libexec/polkitd (No such file or directory)
14.17 Setting up packagekit (1.2.6-5) ...
14.18 invoke-rc.d: could not determine current runlevel
14.19 invoke-rc.d: policy-rc.d denied execution of force-reload.
14.19 Failed to open connection to "system" message bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
14.40 Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
14.40 Setting up packagekit-tools (1.2.6-5) ...
14.40 Setting up software-properties-common (0.99.30-4) ...
14.57 Processing triggers for dbus (1.14.8-2~deb12u1) ...
14.88 Traceback (most recent call last):
14.88   File "/usr/bin/add-apt-repository", line 362, in <module>
14.88     sys.exit(0 if addaptrepo.main() else 1)
14.88                   ^^^^^^^^^^^^^^^^^
14.88   File "/usr/bin/add-apt-repository", line 345, in main
14.88     shortcut = handler(source, **shortcut_params)
14.88                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14.88   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
14.88     return handler(shortcut, **kwargs)
14.88            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
14.88   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
14.88     if self.lpppa.publish_debug_symbols:
14.88        ^^^^^^^^^^
14.88   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
14.88     self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
14.88                   ^^^^^^^^^^^
14.88   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
14.88     self._lpteam = self.lp.people(self.teamname)
14.88                    ^^^^^^^^^^^^^^
14.88 AttributeError: 'NoneType' object has no attribute 'people'
------
failed to solve: process "/bin/sh -c apt-get update &&   apt-get install -y software-properties-common &&   add-apt-repository ppa:deadsnakes/ppa &&   apt-get install -y python3.10 python3-pip curl &&   curl -sSL https://install.python-poetry.org | python3 - &&   apt-get install -y nodejs npm" did not complete successfully: exit code: 1
```

**Comment by adldotori** [comment]
Can you tell where environment you execute it in?

**Comment by shouwangzhe** [comment]
邮件已收到，谢谢！

**Comment by adldotori** [comment]
저는 중국어를 못합니다. 영어로 대답해줄 수 있나요?
